// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi1l2fYm13n4aAzzz3wft9IAA1bAPk8VQ',
    appId: '1:959094681418:web:d1c41c8200fcead6455bb3',
    messagingSenderId: '959094681418',
    projectId: 'flutter-3il',
    authDomain: 'flutter-3il.firebaseapp.com',
    storageBucket: 'flutter-3il.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWpQzrgu5LQN9d2f1aZlJA7D7b6cavlik',
    appId: '1:959094681418:android:eee049f2adb119ac455bb3',
    messagingSenderId: '959094681418',
    projectId: 'flutter-3il',
    storageBucket: 'flutter-3il.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAi1l2fYm13n4aAzzz3wft9IAA1bAPk8VQ',
    appId: '1:959094681418:web:248db6cd1acfe26b455bb3',
    messagingSenderId: '959094681418',
    projectId: 'flutter-3il',
    authDomain: 'flutter-3il.firebaseapp.com',
    storageBucket: 'flutter-3il.firebasestorage.app',
  );
}
